### ISSUE TITLE
Docs development server doesn't run on Windows

### ISSUE THREAD

**Issue by jacobbogers** [apollographql/core-docs#307] opened 2017-07-07 20:13 UTC
$ npm start

> hexo-site@0.0.0 prestart C:\Users\jacob\apollo\core-docs
> npm run build

> hexo-site@0.0.0 build C:\Users\jacob\apollo\core-docs
> cd code; typedoc --json ../docs.json --ignoreCompilerErrors

The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-site@0.0.0 build: `cd code; typedoc --json ../docs.json --ignoreCompilerErrors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hexo-site@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jacob\AppData\Roaming\npm-cache\_logs\2017-07-07T20_12_57_226Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hexo-site@0.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hexo-site@0.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jacob\AppData\Roaming\npm-cache\_logs\2017-07-07T20_12_57_255Z-debug.log

jacob@DESKTOP-J8F8V02 MINGW64 ~/apollo/core-docs (master)
$

**Comment by jacobbogers** [comment] 2017-07-07 20:14
docs.json doesnt exist anywhere, I did exactly like on the readme.md main page
`
git submodule init
git submodule update
cd code && npm install
cd ..
npm install
npm start
`

**Comment by stubailo** [comment] 2017-07-07 20:54
@jacobbogers it sounds like some problem with submodules maybe? Sorry about that.

I think docs.json is the output file though, so maybe the `code` directory doesn't exist?

**Comment by jacobbogers** [comment] 2017-07-08 08:46
SO the installing instructions are wrong or the package is broken. 

The steps from the Readme.md github

1. clone repo works
2. "git submodule init" works (after cd-ing into the repo)
3. "git submdule update" works
3. "cd code" works (you claim this doest work but  "code" exist)
4. "npm install" works
5. "cd .." works
6. "npm install" works
7. "npm start"  (DOES NOT WORK and PREDUCES THE ERROR output I have posted"

**Comment by jacobbogers** [comment] 2017-07-08 09:45
the files in the main dir as you can see `code` directory exist
```
-rw-r--r-- 1 jacob 197121 2212 Jul  7 22:02 _config.yml
drwxr-xr-x 1 jacob 197121    0 Jul  7 22:02 assets/
-rw-r--r-- 1 jacob 197121  379 Jul  7 22:02 circle.yml
drwxr-xr-x 1 jacob 197121    0 Jul  7 22:06 code/
drwxr-xr-x 1 jacob 197121    0 Jul  8 11:44 node_modules/
-rw-r--r-- 1 jacob 197121  894 Jul  7 22:02 package.json
-rw-r--r-- 1 jacob 197121  223 Jul  7 22:02 README.md
drwxr-xr-x 1 jacob 197121    0 Jul  7 22:02 source/
drwxr-xr-x 1 jacob 197121    0 Jul  7 22:02 themes/
```

**Comment by jacobbogers** [comment] 2017-07-08 13:04
Its not working on windows 10, did install on linux CentOS,  no porblems, unfortunatly my laptop is windows 10 and i need to docs offline since i travel alot... this is really shitty, why isnt this bundles into pre-cooked html files, (like postgresql etc) for offline viewing?

**Comment by stubailo** [comment] 2017-07-08 20:36
Sorry, have you considered using a tool for downloading websites to read offline?

**Comment by jacobbogers** [comment] 2017-07-09 13:02
Can you make it work on windows?

**Comment by jacobbogers** [comment] 2017-07-09 13:06
No good free ones. why was hexo choosen instead of jackel?  i am sure someone experienced in hexo can.make this work on windows.  Docs should be OS agnostic.

**Comment by stubailo** [comment] 2017-07-09 21:28
I think the problem is that `typedoc` doesn't work, which is something we use to generate the API docs from TypeScript code. Unfortunately typedoc is pretty janky; I've been thinking about moving off of it since it might be more trouble than it's worth. Using Jekyll wouldn't have helped, since I think the problem is earlier in the pipeline.

We can't always make sure that the development stuff works on Windows since we don't have a lot of people on the team using it. But I would appreciate any PRs to make that happen.

Anyway, I do think you can use a tool like this: http://www.httrack.com/ to download the HTML for offline reading.

**Comment by jacobbogers** [comment] 2017-08-03 17:55
any progress on this?

**Comment by theadactyl** [comment] 2017-12-15 00:33
Closing this issue because the code for core docs has moved to [https://github.com/apollographql/apollo-client/tree/master/docs](https://github.com/apollographql/apollo-client/tree/master/docs)

See it live here:[https://www.apollographql.com/docs/react/](https://www.apollographql.com/docs/react/).

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏

**Closed by theadactyl** 2017-12-15 00:33 UTC
